export const dummySupport = [
  {
    id: 1,
    date: "01-06-2025",
    raisedBy: "Ritika Sharma",
    raisedByType: "User",
    title: "Login Issue on Dashboard",
    type: "Query",
    status: "Open",
    assign: "",
  },
  {
    id: 2,
    date: "02-06-2025",
    raisedBy: "Manas Sharma",
    raisedByType: "Ambassador",
    title: "Feature request: Dark Mode",
    type: "Refund",
    status: "In Progress",
    assign: "",
  },
  {
    id: 3,
    date: "03-06-2025",
    raisedBy: "Ajay Kulhari",
    raisedByType: "User",
    title: "Error on payment page",
    type: "Query",
    status: "Open",
    assign: "",
  },
  {
    id: 4,
    date: "04-06-2025",
    raisedBy: "Neha Gupta",
    raisedByType: "Ambassador",
    title: "Request for new report format",
    type: "Refund",
    status: "Closed",
    assign: "",
  },
  {
    id: 5,
    date: "05-06-2025",
    raisedBy: "Deepak Singh",
    raisedByType: "User",
    title: "Mobile app crashing on login",
    type: "Query",
    status: "In Progress",
    assign: "",
  },
  {
    id: 6,
    date: "06-06-2025",
    raisedBy: "Rohit Bhagat",
    raisedByType: "User",
    title: "Unable to upload documents",
    type: "Query",
    status: "Open",
    assign: "",
  },
  {
    id: 7,
    date: "07-06-2025",
    raisedBy: "Anita Verma",
    raisedByType: "Ambassador",
    title: "Add multi-language support",
    type: "Refund",
    status: "Open",
    assign: "",
  },
  {
    id: 8,
    date: "08-06-2025",
    raisedBy: "Kanishka",
    raisedByType: "User",
    title: "UI glitch on profile page",
    type: "Query",
    status: "Closed",
    assign: "",
  },
];
