export const dummyCommunity = [
  {
    _id: "1",
    sno: 1,
    date: "12-06-2022",
    raisedBy: "John Doe",
    question: "Blog page loading slowly",
    status: "Active",
    assign: "Alice",
    email: "john.doe@example.com",
    phone: "9876543210",
    state: "Delhi",
    role: "User",
    queryType: "Performance",
    source: "Web",
    timeSubmitted: "12:00 PM",
    type: "Ask the Expert",
  },
  {
    _id: "2",
    sno: 2,
    date: "13-06-2022",
    raisedBy: "Jane Smith",
    question: "Unable to post questions",
    status: "Active",
    assign: "Bob",
    email: "jane.smith@example.com",
    phone: "8765432109",
    state: "Maharashtra",
    role: "Contributor",
    queryType: "Posting Issue",
    source: "App",
    timeSubmitted: "12:00 PM",
    type: "Ask the Expert",
  },
  {
    _id: "3",
    sno: 3,
    date: "14-06-2022",
    raisedBy: "Alex Green",
    question: "Images not uploading",
    status: "Active",
    assign: "",
    email: "alex.green@example.com",
    phone: "7654321098",
    state: "Karnataka",
    role: "User",
    queryType: "Media Upload",
    source: "Web",
    timeSubmitted: "12:00 PM",
    type: "Ask the Expert",
  },
  {
    _id: "4",
    sno: 4,
    date: "15-06-2022",
    raisedBy: "Kiran Shah",
    question: "Profile page error",
    status: "Active",
    assign: "",
    email: "kiran.shah@example.com",
    phone: "6543210987",
    state: "Gujarat",
    role: "Moderator",
    queryType: "Bug Report",
    source: "App",
    timeSubmitted: "12:00 PM",
    type: "Ask the Expert",
  },
  {
    _id: "5",
    sno: 5,
    date: "16-06-2022",
    raisedBy: "Nina Rao",
    question: "Commenting not working",
    status: "Active",
    assign: "Charlie",
    email: "nina.rao@example.com",
    phone: "5432109876",
    state: "Tamil Nadu",
    role: "User",
    queryType: "Interaction",
    source: "Web",
    timeSubmitted: "12:00 PM",
    type: "Ask the Expert",
  },
];
