import { XStory } from "@/components/community/XStoriesTable";

export const dummyXStories: XStory[] = [
  {
    sno: 1,
    title: "A Guide To Wildlife Photography",
    videoLink: "www.wildlifephotos.com",
    dateUploaded: "20/06/2025",
    uploadedBy: "John Doe",
    isCoverImage: true,
  },
  {
    sno: 2,
    title: "Mountaineering Basics for Beginners",
    videoLink: "www.climbmore.org",
    dateUploaded: "20/06/2025",
    uploadedBy: "Aisha Khan",
    isCoverImage: false,
  },
  {
    sno: 3,
    title: "Diving with Sharks: My Experience",
    videoLink: "www.sharktales.net",
    dateUploaded: "20/06/2025",
    uploadedBy: "Carlos Rivera",
    isCoverImage: true,
  },
  {
    sno: 4,
    title: "Cycling Through the Alps",
    videoLink: "www.alpineride.com",
    dateUploaded: "20/06/2025",
    uploadedBy: "Mei Wong",
    isCoverImage: false,
  },
  {
    sno: 5,
    title: "Camping Alone in the Sahara",
    videoLink: "www.saharasolo.com",
    dateUploaded: "20/06/2025",
    uploadedBy: "Liam Patel",
    isCoverImage: true,
  },
  {
    sno: 6,
    title: "A Journey Through the Amazon",
    videoLink: "www.amazonadventure.org",
    dateUploaded: "20/06/2025",
    uploadedBy: "Fatima Ahmed",
    isCoverImage: false,
  },
  {
    sno: 7,
    title: "Snowboarding in the Rockies",
    videoLink: "www.snowrush.com",
    dateUploaded: "20/06/2025",
    uploadedBy: "George Liu",
    isCoverImage: true,
  },
  {
    sno: 8,
    title: "Paragliding Across Nepal",
    videoLink: "www.flynepal.com",
    dateUploaded: "20/06/2025",
    uploadedBy: "Saanvi Sharma",
    isCoverImage: true,
  },
  {
    sno: 9,
    title: "Underwater Caves of Mexico",
    videoLink: "www.cavedive.mx",
    dateUploaded: "20/06/2025",
    uploadedBy: "Isaac Brown",
    isCoverImage: false,
  },
  {
    sno: 10,
    title: "Motorbiking Through Vietnam",
    videoLink: "www.ridevietnam.vn",
    dateUploaded: "20/06/2025",
    uploadedBy: "Hannah Cho",
    isCoverImage: true,
  },
];
