import img from "../../public/images/login/login.jpg";

export const dummyEvents = [
  {
    id: 1,
    date: "26-05-2025",
    name: "Kanishka Event",
    status: "Active",
    type: "Workshop",
    organizer: "Manas Sharma",
    location: "Delhi, India",
    img: `${img}`,
  },
  {
    id: 2,
    date: "28-05-2025",
    name: "Ajay Kulhari Event",
    type: "Event",
    status: "Concluded",
    organizer: "Manas Sharma",
    location: "Bihar, India",
    img: `${img}`,
  },
  {
    id: 3,
    date: "28-05-2025",
    name: "Ajay Kulhari Event",
    type: "Event",
    status: "Active",
    organizer: "Manas Sharma",
    location: "Bihar, India",
    img: `${img}`,
  },

  {
    id: 4,
    date: "30-05-2025",
    name: "Ritika Event",
    type: "Exhibition",
    status: "Active",
    organizer: "Manas Sharma",
    location: "Lucknow, India",
    img: `${img}`,
  },
  {
    id: 5,
    date: "01-06-2025",
    name: "Anita Seminar",
    status: "Active",
    type: "Workshop",
    organizer: "Rohan Verma",
    location: "Mumbai, India",
    img: `${img}`,
  },
  {
    id: 6,
    date: "03-06-2025",
    name: "Tech Expo 2025",
    type: "Exhibition",
    status: "Concluded",
    organizer: "Deepak Singh",
    location: "Bangalore, India",
    img: `${img}`,
  },
  {
    id: 7,
    date: "05-06-2025",
    name: "Career Fair",
    type: "Event",
    status: "Active",
    organizer: "Neha Gupta",
    location: "Chennai, India",
    img: `${img}`,
  },
  {
    id: 8,
    date: "07-06-2025",
    name: "Design Thinking Workshop",
    status: "Active",
    type: "Workshop",
    organizer: "Manas Sharma",
    location: "Pune, India",
    img: `${img}`,
  },
  // more rows...
];
