export const PartnersList = [
  {
    sno: 1,
    id: "tarun-khiwal",
    name: "Tarun Khiwal",
    role: "Ambassador",
    city: "Bangalore",
    countryCode: "in",
    upcomingEvents: 2,
    totalEvents: 5,
    fujiGearOwned: 3,
    imageUrl: "https://images.unsplash.com/photo-1603415526960-f7e0328b9c17",
    countryEmoji: "",
    bio: "Award-winning portrait photographer based in Bangalore.",
    tags: ["Portrait", "Culture"],
    about: {
      who: "Tarun Khiwal is an award-winning Indian photographer. He has exhibited work globally.",
      about:
        "Tarun’s visual language focuses on the elegance of Indian heritage. He has worked with global brands and mentored young photographers.",
    },
    gallery: [
      "/public/banner/blog1.png",
      "/public/banner/blog2.png",
      "/public/banner/blog3.png",
    ],
    gear: [
      {
        name: "Fujifilm GFX100S II",
        description: "Large Format Mirrorless Camera",
        image: "https://unsplash.com/photos/black-dslr-camera-lfRlv3nuf78",
        link: "https://fujifilm.in/products/gfx100s-ii/",
      },
      {
        name: "XF500mmF5.6 R LM OIS WR",
        description: "Telephoto Zoom Lens",
        image: "public/banner/GearCamera.png",
        link: "https://fujifilm.in/products/xf500mm/",
      },
    ],
  },
  {
    sno: 2,
    id: "aarti-patel",
    name: "Aarti Patel",
    role: "Evangelist",
    city: "Delhi",
    countryCode: "in",
    upcomingEvents: 1,
    totalEvents: 3,
    fujiGearOwned: 2,
    imageUrl: "https://images.unsplash.com/photo-1503023345310-bd7c1de61c7d",
    countryEmoji: "",
    bio: "Landscape and travel photographer capturing India's beauty.",
    tags: ["Landscape", "Travel"],
    about: {
      who: "Aarti Patel is a passionate landscape artist. She has led photo walks across India.",
      about:
        "Her focus lies in natural light and composition. She’s collaborated with Nikon, later switching to Fujifilm for its color science.",
    },
    gallery: ["/public/banner/blog2.png", "/public/banner/blog3.png"],
    gear: [
      {
        name: "Fujifilm X-S20",
        description: "Compact travel camera",
        image: "public/banner/GearCamera.png",
        link: "https://fujifilm.in/products/x-s20/",
      },
      {
        name: "XF16mmF2.8 R WR",
        description: "Wide angle prime lens",
        image: "public/banner/GearCamera.png",
        link: "https://fujifilm.in/products/xf16mm/",
      },
    ],
  },
  {
    sno: 3,
    id: "ravi-verma",
    name: "Ravi Verma",
    role: "Ambassador",
    city: "Mumbai",
    countryCode: "in",
    upcomingEvents: 0,
    totalEvents: 4,
    fujiGearOwned: 4,
    imageUrl: "https://images.unsplash.com/photo-1527980965255-d3b416303d12",
    countryEmoji: "",
    bio: "Street photographer with a keen eye for urban moments.",
    tags: ["Street", "Candid", "Urban"],
    about: {
      who: "Ravi Verma is known for capturing Mumbai's chaos with authenticity.",
      about:
        "From shooting protests to weddings, Ravi’s candid style stands out. His work has been featured in NatGeo Traveler.",
    },
    gallery: ["/public/banner/blog1.png", "/public/banner/blog3.png"],
    gear: [
      {
        name: "Fujifilm X100VI",
        description: "Compact camera for street photography",
        image: "public/banner/GearCamera.png",
        link: "https://fujifilm.in/products/x100vi/",
      },
      {
        name: "WCL-X100",
        description: "Wide conversion lens",
        image: "public/banner/GearCamera.png",
        link: "https://fujifilm.in/products/wcl-x100-ii/",
      },
    ],
  },
  {
    sno: 4,
    id: "neha-kapoor",
    name: "Neha Kapoor",
    role: "Evangelist",
    city: "Hyderabad",
    countryCode: "in",
    upcomingEvents: 2,
    totalEvents: 6,
    fujiGearOwned: 3,
    imageUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2",
    countryEmoji: "",
    bio: "Nature and wildlife enthusiast telling visual stories.",
    tags: ["Wildlife", "Nature"],
    about: {
      who: "Neha Kapoor is a conservationist and wildlife photographer.",
      about:
        "Neha’s lens brings attention to endangered species in India. She is an ambassador for sustainable photography practices.",
    },
    gallery: ["/public/banner/blog2.png"],
    gear: [
      {
        name: "Fujifilm X-H2S",
        description: "Fast autofocus for wildlife",
        image: "public/banner/GearCamera.png",
        link: "https://fujifilm.in/products/x-h2s/",
      },
      {
        name: "XF 100-400mm",
        description: "Super telephoto zoom lens",
        image: "public/banner/GearCamera.png",
        link: "https://fujifilm.in/products/xf100-400mm/",
      },
    ],
  },
  {
    sno: 5,
    id: "isha-mehta",
    name: "Isha Mehta",
    role: "Ambassador",
    city: "Pune",
    countryCode: "in",
    upcomingEvents: 1,
    totalEvents: 2,
    fujiGearOwned: 2,
    imageUrl: "https://images.unsplash.com/photo-1502767089025-6572583495b9",
    countryEmoji: "",
    bio: "Documentary filmmaker using stills to support her narratives.",
    tags: ["Documentary", "Storytelling"],
    about: {
      who: "Isha Mehta blends documentary photography with cinema.",
      about:
        "She has worked on social issue documentaries. Her photos often serve as mood boards for larger visual projects.",
    },
    gallery: ["/public/banner/blog1.png", "/public/banner/blog3.png"],
    gear: [
      {
        name: "Fujifilm X-T4",
        description: "Great for hybrid photo/video shooters",
        image: "public/banner/GearCamera.png",
        link: "https://fujifilm.in/products/x-t4/",
      },
      {
        name: "XF 23mm F2",
        description: "Everyday documentary lens",
        image: "public/banner/GearCamera.png",
        link: "https://fujifilm.in/products/xf23mm/",
      },
    ],
  },
];
