export const PartnersList = [
  {
    sno: 1,
    name: "Tarun Khiwal",
    role: "Ambassador",
    city: "Bangalore",
    countryCode: "in",
    upcomingEvents: 2,
    totalEvents: 5,
    fujiGearOwned: 3,
    imageUrl: "https://images.unsplash.com/photo-1603415526960-f7e0328b9c17",
    countryEmoji: "",
  },
  {
    sno: 2,
    name: "Aarti Patel",
    role: "Evangelist",
    city: "Delhi",
    countryCode: "in",
    upcomingEvents: 1,
    totalEvents: 3,
    fujiGearOwned: 2,
    imageUrl: "https://images.unsplash.com/photo-1503023345310-bd7c1de61c7d",
    countryEmoji: "",
  },
  {
    sno: 3,
    name: "Ravi Verma",
    role: "Ambassador",
    city: "Mumbai",
    countryCode: "in",
    upcomingEvents: 0,
    totalEvents: 4,
    fujiGearOwned: 4,
    imageUrl: "https://images.unsplash.com/photo-1527980965255-d3b416303d12",
    countryEmoji: "",
  },
  {
    sno: 4,
    name: "Neha Kapoor",
    role: "Evangelist",
    city: "Hyderabad",
    countryCode: "in",
    upcomingEvents: 2,
    totalEvents: 6,
    fujiGearOwned: 3,
    imageUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2",
    countryEmoji: "",
  },
  {
    sno: 5,
    name: "Isha Mehta",
    role: "Ambassador",
    city: "Pune",
    countryCode: "in",
    upcomingEvents: 1,
    totalEvents: 2,
    fujiGearOwned: 2,
    imageUrl: "https://images.unsplash.com/photo-1502767089025-6572583495b9",
    countryEmoji: "",
  },
];
